server:
  port: 8081
hm:
  swagger:
    title: 商品接口文档
    package: com.hmall.item.controller
  db:
    database: hm-item
spring:
  redis:
    host: 192.168.181.128
    port: 6379
    password: 123456
    database: 1
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090
      http-method-specify: true # 开启请求方式前缀,否则所有请求方式无法区分来操作
